version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aimarkethub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aimarket-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - aimarket-net

  backend:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/aimarkethub
      REDIS_URL: redis://redis:6379/0
      OPENAI_KEY: ${OPENAI_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - aimarket-net

  worker:
    build: ./processing
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/aimarkethub
      REDIS_URL: redis://redis:6379/0
      OPENAI_KEY: ${OPENAI_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - aimarket-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://backend:8000
    depends_on:
      - backend
    networks:
      - aimarket-net

volumes:
  pgdata:

networks:
  aimarket-net:
    driver: bridge 